# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-15 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metronus_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='short_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
