# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-13 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metronus_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('registryDate', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('actor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metronus_app.Actor')),
                ('projectDepartment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metronus_app.ProjectDepartment')),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='company'),
        ),
        migrations.AlterField(
            model_name='projectdepartmentemployeerole',
            name='roleDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set([('name', 'company_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('name', 'company_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('projectDepartment_id', 'name')]),
        ),
    ]
