# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metronus_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='picture',
            field=models.ImageField(blank=True, default='/home/usuario/Desktop/metronus/Metronus-Project/metronus/static/avatar.png', null=True, upload_to='actor'),
        ),
    ]
