# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metronus_app', '0002_auto_20170316_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='picture',
            field=models.ImageField(blank=True, default='/static/avatar.png', null=True, upload_to='actor'),
        ),
    ]
